# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
# IP: The module: 'design_1_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
# IP: The module: 'design_1_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/test/250513_Microblaze_GPIO/250513_Microblaze_GPIO.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
